In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


games = pd.read_csv('games.csv')
players = pd.read_csv('players.csv')
plays = pd.read_csv('plays.csv')
# tackels = pd.read_csv('tackles.csv')
first_week = pd.read_csv('tracking_week_1.csv')

In [16]:
games.loc[((games['homeTeamAbbr'] == 'LA') & (games['visitorTeamAbbr'] == 'BUF')) | ((games['homeTeamAbbr'] == 'BUF') & (games['visitorTeamAbbr'] == 'LA'))]

       gameId  season  week    gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  homeFinalScore  visitorFinalScore
0  2022090800    2022     1  09/08/2022        20:20:00           LA             BUF              10                 31

In [14]:
games

         gameId  season  week    gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  homeFinalScore  visitorFinalScore
0    2022090800    2022     1  09/08/2022        20:20:00           LA             BUF              10                 31
1    2022091100    2022     1  09/11/2022        13:00:00          ATL              NO              26                 27
2    2022091101    2022     1  09/11/2022        13:00:00          CAR             CLE              24                 26
3    2022091102    2022     1  09/11/2022        13:00:00          CHI              SF              19                 10
4    2022091103    2022     1  09/11/2022        13:00:00          CIN             PIT              20                 23
5    2022091104    2022     1  09/11/2022        13:00:00          DET             PHI              35                 38
6    2022091105    2022     1  09/11/2022        13:00:00          HOU             IND              20                 20
7    2022091106    2022     1  09/11/2022        13:00:00          MIA              NE              20                  7
8    2022091107    2022     1  09/11/2022        13:00:00          NYJ             BAL               9                 24
9    2022091109    2022     1  09/11/2022        13:00:00          WAS             JAX              28                 22
10   2022091110    2022     1  09/11/2022        16:25:00          ARI              KC              21                 44
11   2022091111    2022     1  09/11/2022        16:25:00          LAC              LV              24                 19
12   2022091112    2022     1  09/11/2022        16:25:00          MIN              GB              23                  7
13   2022091108    2022     1  09/11/2022        16:25:00          TEN             NYG              20                 21
14   2022091113    2022     1  09/11/2022        20:20:00          DAL              TB               3                 19
15   2022091200    2022     1  09/12/2022        20:15:00          SEA             DEN              17                 16
16   2022091500    2022     2  09/15/2022        20:15:00           KC             LAC              27                 24
17   2022091800    2022     2  09/18/2022        13:00:00          BAL             MIA              38                 42
18   2022091801    2022     2  09/18/2022        13:00:00          CLE             NYJ              30                 31
19   2022091802    2022     2  09/18/2022        13:00:00          DET             WAS              36                 27
20   2022091803    2022     2  09/18/2022        13:00:00          JAX             IND              24                  0
21   2022091804    2022     2  09/18/2022        13:00:00           NO              TB              10                 20
22   2022091805    2022     2  09/18/2022        13:00:00          NYG             CAR              19                 16
23   2022091806    2022     2  09/18/2022        13:00:00          PIT              NE              14                 17
24   2022091807    2022     2  09/18/2022        16:05:00           LA             ATL              31                 27
25   2022091808    2022     2  09/18/2022        16:05:00           SF             SEA              27                  7
26   2022091809    2022     2  09/18/2022        16:25:00          DAL             CIN              20                 17
27   2022091810    2022     2  09/18/2022        16:25:00          DEN             HOU              16                  9
28   2022091811    2022     2  09/18/2022        16:25:00           LV             ARI              23                 29
29   2022091812    2022     2  09/18/2022        20:20:00           GB             CHI              27                 10
30   2022091900    2022     2  09/19/2022        19:15:00          BUF             TEN              41                  7
31   2022091901    2022     2  09/19/2022        20:30:00          PHI             MIN              24                  7
32   2022092200    2022     3  09/22/2022        20:15:00          CLE             PIT              29                 17
33   2022092500    2022     3  09/25/2022        13:00:00          CAR              NO              22                 14
34   2022092501    2022     3  09/25/2022        13:00:00          CHI             HOU              23                 20
35   2022092502    2022     3  09/25/2022        13:00:00          IND              KC              20                 17
36   2022092503    2022     3  09/25/2022        13:00:00          MIA             BUF              21                 19
37   2022092504    2022     3  09/25/2022        13:00:00          MIN             DET              28                 24
38   2022092505    2022     3  09/25/2022        13:00:00           NE             BAL              26                 37
39   2022092506    2022     3  09/25/2022        13:00:00          NYJ             CIN              12                 27
40   2022092507    2022     3  09/25/2022        13:00:00          TEN              LV              24                 22
41   2022092508    2022     3  09/25/2022        13:00:00          WAS             PHI               8                 24
42   2022092509    2022     3  09/25/2022        16:05:00          LAC             JAX              10                 38
43   2022092510    2022     3  09/25/2022        16:25:00          ARI              LA              12                 20
44   2022092511    2022     3  09/25/2022        16:25:00          SEA             ATL              23                 27
45   2022092512    2022     3  09/25/2022        16:25:00           TB              GB              12                 14
46   2022092513    2022     3  09/25/2022        20:20:00          DEN              SF              11                 10
47   2022092600    2022     3  09/26/2022        20:15:00          NYG             DAL              16                 23
48   2022092900    2022     4  09/29/2022        20:15:00          CIN             MIA              27                 15
49   2022100200    2022     4  10/02/2022        09:30:00           NO             MIN              25                 28
50   2022100201    2022     4  10/02/2022        13:00:00          ATL             CLE              23                 20
51   2022100202    2022     4  10/02/2022        13:00:00          BAL             BUF              20                 23
52   2022100204    2022     4  10/02/2022        13:00:00          DAL             WAS              25                 10
53   2022100205    2022     4  10/02/2022        13:00:00          DET             SEA              45                 48
54   2022100206    2022     4  10/02/2022        13:00:00          HOU             LAC              24                 34
55   2022100207    2022     4  10/02/2022        13:00:00          IND             TEN              17                 24
56   2022100208    2022     4  10/02/2022        13:00:00          NYG             CHI              20                 12
57   2022100209    2022     4  10/02/2022        13:00:00          PHI             JAX              29                 21
58   2022100210    2022     4  10/02/2022        13:00:00          PIT             NYJ              20                 24
59   2022100203    2022     4  10/02/2022        16:05:00          CAR             ARI              16                 26
60   2022100211    2022     4  10/02/2022        16:25:00           GB              NE              27                 24
61   2022100212    2022     4  10/02/2022        16:25:00           LV             DEN              32                 23
62   2022100213    2022     4  10/02/2022        20:20:00           TB              KC              31                 41
63   2022100300    2022     4  10/03/2022        20:15:00           SF              LA              24                  9
64   2022100600    2022     5  10/06/2022        20:15:00          DEN             IND               9                 12
65   2022100900    2022     5  10/09/2022        09:30:00           GB             NYG              22                 27
66   2022100901    2022     5  10/09/2022        13:00:00          BUF             PIT              38                  3
67   2022100902    2022     5  10/09/2022        13:00:00          CLE             LAC              28                 30
68   2022100903    2022     5  10/09/2022        13:00:00          JAX             HOU               6                 13
69   2022100904    2022     5  10/09/2022        13:00:00          MIN             CHI              29                 22
70   2022100905    2022     5  10/09/2022        13:00:00           NE             DET              29                  0
71   2022100906    2022     5  10/09/2022        13:00:00           NO             SEA              39                 32
72   2022100907    2022     5  10/09/2022        13:00:00          NYJ             MIA              40                 17
73   2022100908    2022     5  10/09/2022        13:00:00           TB             ATL              21                 15
74   2022100909    2022     5  10/09/2022        13:00:00          WAS             TEN              17                 21
75   2022100910    2022     5  10/09/2022        16:05:00          CAR              SF              15                 37
76   2022100911    2022     5  10/09/2022        16:25:00          ARI             PHI              17                 20
77   2022100912    2022     5  10/09/2022        16:25:00           LA             DAL              10                 22
78   2022100913    2022     5  10/09/2022        20:20:00          BAL             CIN              19                 17
79   2022101000    2022     5  10/10/2022        20:15:00           KC              LV              30                 29
80   2022101300    2022     6  10/13/2022        20:15:00          CHI             WAS               7                 12
81   2022101600    2022     6  10/16/2022        13:00:00          ATL              SF              28                 14
82   2022101601    2022     6  10/16/2022        13:00:00          CLE              NE              15                 38
83   2022101602    2022     6  10/16/2022        13:00:00           GB             NYJ              10                 27
84   2022101603    2022     6  10/16/2022        13:00:00          IND             JAX              34                 27
85   2022101604    2022     6  10/16/2022        13:00:00          MIA             MIN              16                 24
86   2022101605    2022     6  10/16/2022        13:00:00           NO             CIN              26                 30
87   2022101606    2022     6  10/16/2022        13:00:00          NYG             BAL              24                 20
88   2022101607    2022     6  10/16/2022        13:00:00          PIT              TB              20                 18
89   2022101608    2022     6  10/16/2022        16:05:00           LA             CAR              24                 10
90   2022101609    2022     6  10/16/2022        16:05:00          SEA             ARI              19                  9
91   2022101610    2022     6  10/16/2022        16:25:00           KC             BUF              20                 24
92   2022101611    2022     6  10/16/2022        20:20:00          PHI             DAL              26                 17
93   2022101700    2022     6  10/17/2022        20:15:00          LAC             DEN              19                 16
94   2022102000    2022     7  10/20/2022        20:15:00          ARI              NO              42                 34
95   2022102300    2022     7  10/23/2022        13:00:00          BAL             CLE              23                 20
96   2022102301    2022     7  10/23/2022        13:00:00          CAR              TB              21                  3
97   2022102302    2022     7  10/23/2022        13:00:00          CIN             ATL              35                 17
98   2022102303    2022     7  10/23/2022        13:00:00          DAL             DET              24                  6
99   2022102304    2022     7  10/23/2022        13:00:00          JAX             NYG              17                 23
100  2022102305    2022     7  10/23/2022        13:00:00          TEN             IND              19                 10
101  2022102306    2022     7  10/23/2022        13:00:00          WAS              GB              23                 21
102  2022102307    2022     7  10/23/2022        16:05:00          DEN             NYJ               9                 16
103  2022102308    2022     7  10/23/2022        16:05:00           LV             HOU              38                 20
104  2022102309    2022     7  10/23/2022        16:25:00          LAC             SEA              23                 37
105  2022102310    2022     7  10/23/2022        16:25:00           SF              KC              23                 44
106  2022102311    2022     7  10/23/2022        20:20:00          MIA             PIT              16                 10
107  2022102400    2022     7  10/24/2022        20:15:00           NE             CHI              14                 33
108  2022102700    2022     8  10/27/2022        20:15:00           TB             BAL              22                 27
109  2022103000    2022     8  10/30/2022        09:30:00          JAX             DEN              17                 21
110  2022103001    2022     8  10/30/2022        13:00:00          ATL             CAR              37                 34
111  2022103002    2022     8  10/30/2022        13:00:00          DAL             CHI              49                 29
112  2022103003    2022     8  10/30/2022        13:00:00          DET             MIA              27                 31
113  2022103005    2022     8  10/30/2022        13:00:00          MIN             ARI              34                 26
114  2022103006    2022     8  10/30/2022        13:00:00           NO              LV              24                  0
115  2022103007    2022     8  10/30/2022        13:00:00          NYJ              NE              17                 22
116  2022103008    2022     8  10/30/2022        13:00:00          PHI             PIT              35                 13
117  2022103004    2022     8  10/30/2022        16:05:00          HOU             TEN              10                 17
118  2022103009    2022     8  10/30/2022        16:25:00          IND             WAS              16                 17
119  2022103010    2022     8  10/30/2022        16:25:00           LA              SF              14                 31
120  2022103011    2022     8  10/30/2022        16:25:00          SEA             NYG              27                 13
121  2022103012    2022     8  10/30/2022        20:20:00          BUF              GB              27                 17
122  2022103100    2022     8  10/31/2022        20:15:00          CLE             CIN              32                 13
123  2022110300    2022     9  11/03/2022        20:15:00          HOU             PHI              17                 29
124  2022110600    2022     9  11/06/2022        13:00:00          ATL             LAC              17                 20
125  2022110601    2022     9  11/06/2022        13:00:00          CHI             MIA              32                 35
126  2022110602    2022     9  11/06/2022        13:00:00          CIN             CAR              42                 21
127  2022110603    2022     9  11/06/2022        13:00:00          DET              GB              15                  9
128  2022110604    2022     9  11/06/2022        13:00:00          JAX              LV              27                 20
129  2022110605    2022     9  11/06/2022        13:00:00           NE             IND              26                  3
130  2022110606    2022     9  11/06/2022        13:00:00          NYJ             BUF              20                 17
131  2022110607    2022     9  11/06/2022        13:00:00          WAS             MIN              17                 20
132  2022110608    2022     9  11/06/2022        16:05:00          ARI             SEA              21                 31
133  2022110609    2022     9  11/06/2022        16:25:00           TB              LA              16                 13
134  2022110610    2022     9  11/06/2022        20:20:00           KC             TEN              20                 17
135  2022110700    2022     9  11/07/2022        20:15:00           NO             BAL              13                 27

In [13]:
plays

           gameId  playId  ballCarrierId ballCarrierDisplayName                                    playDescription  quarter  down  yardsToGo possessionTeam defensiveTeam yardlineSide  yardlineNumber gameClock  preSnapHomeScore  preSnapVisitorScore passResult  passLength  penaltyYards  prePenaltyPlayResult  playResult playNullifiedByPenalty  absoluteYardlineNumber offenseFormation  defendersInTheBox  passProbability  preSnapHomeTeamWinProbability  preSnapVisitorTeamWinProbability  homeTeamWinProbabilityAdded  visitorTeamWinProbilityAdded  expectedPoints  expectedPointsAdded foulName1 foulName2  foulNFLId1  foulNFLId2
0      2022100908    3537          48723           Parker Hesse  (7:52) (Shotgun) M.Mariota pass short middle t...        4     1         10            ATL            TB          ATL              41      7:52                21                    7          C         6.0           NaN                     9           9                      N                      69          SHOTGUN                7.0         0.747284                       0.976785                          0.023215                    -0.006110                      0.006110        2.360609             0.981955       NaN       NaN         NaN         NaN
1      2022091103    3126          52457         Chase Claypool  (7:38) (Shotgun) C.Claypool right end to PIT 3...        4     1         10            PIT           CIN          PIT              34      7:38                14                   20        NaN         NaN           NaN                     3           3                      N                      76          SHOTGUN                7.0         0.416454                       0.160485                          0.839515                    -0.010865                      0.010865        1.733344            -0.263424       NaN       NaN         NaN         NaN
2      2022091111    1148          42547          Darren Waller  (8:57) D.Carr pass short middle to D.Waller to...        2     2          5             LV           LAC           LV              30      8:57                10                    3          C        11.0           NaN                    15          15                      N                      40           I_FORM                6.0         0.267933                       0.756661                          0.243339                    -0.037409                      0.037409        1.312855             1.133666       NaN       NaN         NaN         NaN
3      2022100212    2007          46461             Mike Boone  (13:12) M.Boone left tackle to DEN 44 for 7 ya...        3     2         10            DEN            LV          DEN              37     13:12                19                   16        NaN         NaN           NaN                     7           7                      N                      47       SINGLEBACK                6.0         0.592704                       0.620552                          0.379448                    -0.002451                      0.002451        1.641006            -0.043580       NaN       NaN         NaN         NaN
4      2022091900    1372          47857       Devin Singletary  (8:33) D.Singletary right guard to TEN 32 for ...        2     1         10            BUF           TEN          TEN              35      8:33                 7                    7        NaN         NaN           NaN                     3           3                      N                      75           I_FORM                7.0         0.470508                       0.836290                          0.163710                     0.001053                     -0.001053        3.686428            -0.167903       NaN       NaN         NaN         NaN
...           ...     ...            ...                    ...                                                ...      ...   ...        ...            ...           ...          ...             ...       ...               ...                  ...        ...         ...           ...                   ...         ...                    ...                     ...              ...                ...              ...                            ...                               ...                          ...                           ...             ...                  ...       ...       ...         ...         ...
12481  2022100204     123          43293        Ezekiel Elliott  (13:31) E.Elliott right tackle to WAS 38 for 1...        1     1         10            DAL           WAS          WAS              39     13:31                 0                    0        NaN         NaN           NaN                     1           1                      N                      49       SINGLEBACK                6.0         0.577800                       0.638600                          0.361400                    -0.011542                      0.011542        3.642571            -0.504018       NaN       NaN         NaN         NaN
12482  2022091200    3467          46189            Will Dissly  (6:08) G.Smith pass short right to W.Dissly to...        4     1         10            SEA           DEN          SEA              30      6:08                17                   16          C         0.0           NaN                     2           2                      N                      40       SINGLEBACK                7.0         0.298983                       0.615241                          0.384759                    -0.025458                      0.025458        1.434580            -0.444642       NaN       NaN         NaN         NaN
12483  2022101605    3371          44860              Joe Mixon  (9:35) (Shotgun) J.Mixon left end to CIN 47 fo...        4     1         10            CIN            NO          CIN              41      9:35                26                   21        NaN         NaN           NaN                     6           6                      N                      69          SHOTGUN                6.0         0.639439                       0.667054                          0.332946                    -0.005164                      0.005164        2.115356             0.203819       NaN       NaN         NaN         NaN
12484  2022100207    2777          52449        Jonathan Taylor  (2:02) (Shotgun) J.Taylor up the middle to TEN...        3     1         10            IND           TEN          TEN              34      2:02                17                   24        NaN         NaN           NaN                    -2          -2                      N                      44          SHOTGUN                6.0         0.518695                       0.410611                          0.589389                    -0.046648                      0.046648        3.946232            -0.976039       NaN       NaN         NaN         NaN
12485  2022102308     905          54572          Dameon Pierce  (12:51) C.Heck reported in as eligible.  D.Pie...        2     3          1            HOU            LV           LV              17     12:51                 3                    0        NaN         NaN           NaN                     3           3                      N                      27           I_FORM                8.0         0.101552                       0.726639                          0.273361                    -0.015028                      0.015028        4.685974             0.251580       NaN       NaN         NaN         NaN

[12486 rows x 35 columns]

In [20]:
len(plays)

12486

In [21]:
plays.loc[plays['gameId'] == 2022100908]

           gameId  playId  ballCarrierId ballCarrierDisplayName                                    playDescription  quarter  down  yardsToGo possessionTeam defensiveTeam yardlineSide  yardlineNumber gameClock  preSnapHomeScore  preSnapVisitorScore passResult  passLength  penaltyYards  prePenaltyPlayResult  playResult playNullifiedByPenalty  absoluteYardlineNumber offenseFormation  defendersInTheBox  passProbability  preSnapHomeTeamWinProbability  preSnapVisitorTeamWinProbability  homeTeamWinProbabilityAdded  visitorTeamWinProbilityAdded  expectedPoints  expectedPointsAdded                  foulName1 foulName2  foulNFLId1  foulNFLId2
0      2022100908    3537          48723           Parker Hesse  (7:52) (Shotgun) M.Mariota pass short middle t...        4     1         10            ATL            TB          ATL              41      7:52                21                    7          C         6.0           NaN                     9           9                      N                      69          SHOTGUN                7.0         0.747284                       0.976785                          0.023215                    -0.006110                      0.006110        2.360609             0.981955                        NaN       NaN         NaN         NaN
27     2022100908     619          54042          Caleb Huntley  (4:52) (Shotgun) C.Huntley left end to ATL 14 ...        1     1         10            ATL            TB          ATL              15      4:52                 0                    0        NaN         NaN           NaN                    -1          -1                      N                      25           PISTOL                7.0         0.732525                       0.773485                          0.226515                     0.011477                     -0.011477        0.598683            -1.130062                        NaN       NaN         NaN         NaN
156    2022100908    3731          48374      Olamide Zaccheaus  (4:43) (Shotgun) M.Mariota pass short left to ...        4     1         10            ATL            TB           TB              19      4:43                21                    7          C         7.0           NaN                    19          19                      N                      29          SHOTGUN                6.0         0.775222                       0.976926                          0.023074                    -0.025315                      0.025315        4.727719             2.272281                        NaN       NaN         NaN         NaN
241    2022100908    1821          42345         Marcus Mariota  (1:10) (Shotgun) M.Mariota scrambles left end ...        2     1         10            ATL            TB          ATL              32      1:10                10                    0          R         NaN           NaN                     8           8                      N                      78           PISTOL                7.0         0.789536                       0.927155                          0.072845                    -0.001738                      0.001738        1.145732             0.163629                        NaN       NaN         NaN         NaN
267    2022100908    2392          44816      Leonard Fournette  (10:28) (Shotgun) L.Fournette left guard to TB...        3     1         10             TB           ATL           TB              26     10:28                13                    0        NaN         NaN           NaN                     2           2                      N                      84          SHOTGUN                6.0         0.459837                       0.969834                          0.030166                    -0.000411                      0.000411        1.361218            -0.559195                        NaN       NaN         NaN         NaN
317    2022100908      85          44816      Leonard Fournette  (14:53) L.Fournette left tackle to TB 33 for 1...        1     2         10             TB           ATL           TB              19     14:53                 0                    0        NaN         NaN           NaN                    14          14                      N                      91           I_FORM                7.0         0.519393                       0.772355                          0.227645                     0.035776                     -0.035776        0.059223             1.663898                        NaN       NaN         NaN         NaN
345    2022100908    1474          46263           Russell Gage  (5:07) (Shotgun) T.Brady pass short middle to ...        2     2         10             TB           ATL           TB              13      5:07                 7                    0          C         6.0           NaN                    14          14                      N                      23            EMPTY                5.0         0.484796                       0.911165                          0.088835                     0.006685                     -0.006685       -0.165997             1.357837                        NaN       NaN         NaN         NaN
379    2022100908    1180          44816      Leonard Fournette  (9:34) (No Huddle) L.Fournette right guard for...        2     1          1             TB           ATL          ATL               1      9:34                 0                    0        NaN         NaN           NaN                     1           1                      N                     109       SINGLEBACK                8.0         0.209036                       0.864340                          0.135660                     0.022428                     -0.022428        6.409568             0.590432                        NaN       NaN         NaN         NaN
506    2022100908    2968          54042          Caleb Huntley  (:56) (Shotgun) C.Huntley left tackle to TB 15...        3     1          5            ATL            TB           TB              16      0:56                21                    0        NaN         NaN           NaN                     1           1                      N                      94           PISTOL                7.0         0.675579                       0.983117                          0.016883                     0.002158                     -0.002158        5.195197            -0.180825                        NaN       NaN         NaN         NaN
657    2022100908    3635          54473           Drake London  (5:50) (Shotgun) M.Mariota pass short right to...        4     2         10            ATL            TB           TB              42      5:50                21                    7          C        11.0           NaN                    13          13                      N                      52          SHOTGUN                6.0         0.902529                       0.979716                          0.020284                    -0.002619                      0.002619        3.020971             1.206591                        NaN       NaN         NaN         NaN
717    2022100908    1046          44816      Leonard Fournette  (12:12) (Shotgun) T.Brady pass short left to L...        2     2         10             TB           ATL          ATL              44     12:12                 0                    0          C         0.0           NaN                     7           7                      N                      66          SHOTGUN                7.0         0.810015                       0.821374                          0.178626                     0.000949                     -0.000949        2.501759             0.000750                        NaN       NaN         NaN         NaN
958    2022100908     640          54616         Tyler Allgeier  (4:09) (Shotgun) T.Allgeier left end to ATL 31...        1     2         11            ATL            TB          ATL              14      4:09                 0                    0        NaN         NaN           NaN                    17          17                      N                      24           PISTOL                7.0         0.806074                       0.784962                          0.215038                    -0.040876                      0.040876       -0.531380             1.781197                        NaN       NaN         NaN         NaN
1112   2022100908    3702          54473           Drake London  (4:47) (Shotgun) M.Mariota pass short right to...        4     3          7            ATL            TB           TB              26      4:47                21                    7          C         6.0           NaN                     7           7                      N                      36          SHOTGUN                6.0         0.987231                       0.983540                          0.016460                    -0.006614                      0.006614        3.366159             1.361560                        NaN       NaN         NaN         NaN
1130   2022100908    2875          44816      Leonard Fournette  (2:41) (No Huddle, Shotgun) T.Brady pass short...        3     3         16             TB           ATL           TB               7      2:41                21                    0          C        -1.0           NaN                    12          12                      N                     103          SHOTGUN                6.0         0.627407                       0.990743                          0.009257                     0.000537                     -0.000537       -2.366872             0.137519                        NaN       NaN         NaN         NaN
1221   2022100908    1322          54042          Caleb Huntley  (7:59) (Shotgun) C.Huntley up the middle to AT...        2     2          3            ATL            TB          ATL              43      7:59                 7                    0        NaN         NaN           NaN                     3           3                      N                      67           PISTOL                8.0         0.336160                       0.879076                          0.120924                    -0.002728                      0.002728        2.217223             0.372554                        NaN       NaN         NaN         NaN
1272   2022100908    3614          53612         Avery Williams  (6:27) (Shotgun) A.Williams up the middle to T...        4     1         10            ATL            TB           TB              42      6:27                21                    7        NaN         NaN           NaN                     0           0                      N                      52          SHOTGUN                8.0         0.786006                       0.975316                          0.024684                     0.004401                     -0.004401        3.512958            -0.491987                        NaN       NaN         NaN         NaN
1280   2022100908    3474          54616         Tyler Allgeier  (9:49) (Shotgun) T.Allgeier up the middle to A...        4     1         10            ATL            TB          ATL              30      9:49                21                    7        NaN         NaN           NaN                     2           2                      N                      80           PISTOL                7.0         0.781400                       0.974507                          0.025493                     0.003577                     -0.003577        1.747712            -0.366227                        NaN       NaN         NaN         NaN
1327   2022100908    2035          44816      Leonard Fournette  (:09) (Shotgun) T.Brady pass short right to L....        2     1         10             TB           ATL          ATL              47      0:09                10                    0          C         4.0           NaN                    21          21                      N                      63          SHOTGUN                5.0         0.939284                       0.942263                          0.057737                     0.010277                     -0.010277        0.672745             1.371552                        NaN       NaN         NaN         NaN
1616   2022100908    3029          54616         Tyler Allgeier  (15:00) (Shotgun) T.Allgeier up the middle to ...        4     3          3            ATL            TB           TB              14     15:00                21                    0        NaN         NaN           NaN                     4           4                      N                      24           PISTOL                8.0         0.912970                       0.987424                          0.012576                    -0.000920                      0.000920        4.314864             0.908717                        NaN       NaN         NaN         NaN
1756   2022100908     909          54556          Rachaad White  (14:01) (No Huddle, Shotgun) T.Brady pass shor...        2     1         10             TB           ATL           TB              26     14:01                 0                    0          C         5.0           NaN                     9           9                      N                      36          SHOTGUN                7.0         0.683872                       0.803978                          0.196022                     0.012519                     -0.012519        1.225853             0.624648                        NaN       NaN         NaN         NaN
1921   2022100908    3288          54042          Caleb Huntley  (12:03) C.Huntley right tackle to TB 45 for 6 ...        4     2          7            ATL            TB          ATL              49     12:03                21                    7        NaN         NaN         -15.0                     6         -15                      Y                      61           I_FORM                7.0              NaN                       0.970854                          0.029146                     0.004457                     -0.004457        2.447664            -1.460156                  Face Mask       NaN     45550.0         NaN
2160   2022100908    1498          54571             Cade Otton  (4:41) (No Huddle, Shotgun) T.Brady pass short...        2     1         10             TB           ATL           TB              27      4:41                 7                    0          C         1.0           NaN                     7           7                      N                      37          SHOTGUN                6.0         0.501198                       0.917851                          0.082149                     0.000872                     -0.000872        1.191840             0.081856                        NaN       NaN         NaN         NaN
2348   2022100908    2534          54571             Cade Otton  (8:13) (Shotgun) T.Brady pass short right to C...        3     1         10             TB           ATL           TB              48      8:13                13                    0          C         3.0           NaN                     3           3                      N                      62          SHOTGUN                6.0         0.450586                       0.971548                          0.028452                    -0.000356                      0.000356        2.892326            -0.254743                        NaN       NaN         NaN         NaN
2536   2022100908    2213          54616         Tyler Allgeier  (14:01) (No Huddle, Shotgun) M.Mariota pass sh...        3     3          6            ATL            TB          ATL              22     14:01                13                    0          C        -2.0          -5.0                    17          -5                      Y                      32           PISTOL                7.0              NaN                       0.951064                          0.048936                     0.006920                     -0.006920       -0.590418            -0.735292  Ineligible Downfield Pass       NaN     45550.0         NaN
2632   2022100908    1616          41233             Mike Evans  (2:49) (No Huddle, Shotgun) T.Brady pass short...        2     2         10             TB           ATL          ATL              24      2:49                 7                    0          C         7.0           NaN                     7           7                      N                      86          SHOTGUN                6.0         0.562714                       0.931414                          0.068586                     0.001232                     -0.001232        3.556705             0.384055                        NaN       NaN         NaN         NaN
2741   2022100908    2924          54042          Caleb Huntley  (1:43) C.Huntley right guard to TB 21 for 22 y...        3     1         10            ATL            TB           TB              43      1:43                21                    0        NaN         NaN           NaN                    22          22                      N                      67           I_FORM                7.0         0.358063                       0.987377                          0.012623                    -0.002754                      0.002754        3.421862             1.323609                        NaN       NaN         NaN         NaN
2816   2022100908    1842          48374      Olamide Zaccheaus  (:47) (No Huddle, Shotgun) M.Mariota pass deep...        2     2          2            ATL            TB          ATL              40      0:47                10                    0          C        18.0          15.0                    20          35                      N                      70           PISTOL                8.0         0.860953                       0.925417                          0.074583                    -0.012656                      0.012656        1.309361             2.631701        Roughing the Passer       NaN     46081.0         NaN
2829   2022100908     435          44816      Leonard Fournette  (8:49) (Shotgun) T.Brady pass short right to L...        1     1         10             TB           ATL          ATL              48      8:49                 0                    0          C        -6.0           NaN                    11          11                      N                      58           PISTOL                6.0         0.747282                       0.835976                          0.164024                     0.004964                     -0.004964        3.106878             0.682892                        NaN       NaN         NaN         NaN
2920   2022100908     369          44816      Leonard Fournette  (10:43) (Shotgun) L.Fournette left guard to TB...        1     1         10             TB           ATL           TB              23     10:43                 0                    0        NaN         NaN           NaN                     6           6                      N                      87          SHOTGUN                6.0         0.666604                       0.811534                          0.188466                     0.001165                     -0.001165        1.057170             0.182128                        NaN       NaN         NaN         NaN
2921   2022100908    3146          46263           Russell Gage  (13:36) (Shotgun) T.Brady pass short right to ...        4     2         10             TB           ATL           TB              25     13:36                21                    7          C         4.0           NaN                     6           6                      N                      35          SHOTGUN                7.0         0.506079                       0.978221                          0.021779                    -0.000615                      0.000615        0.568238            -0.489966                        NaN       NaN         NaN         NaN

In [2]:
first_week.loc[first_week['playId'] == ]

             gameId  playId    nflId     displayName  frameId                        time  jerseyNumber      club playDirection          x      y     s     a   dis       o     dir         event
0        2022090800      56  35472.0  Rodger Saffold        1  2022-09-08 20:24:05.200000          76.0       BUF          left  88.370000  27.27  1.62  1.15  0.16  231.74  147.90           NaN
1        2022090800      56  35472.0  Rodger Saffold        2  2022-09-08 20:24:05.299999          76.0       BUF          left  88.470000  27.13  1.67  0.61  0.17  230.98  148.53  pass_arrived
2        2022090800      56  35472.0  Rodger Saffold        3  2022-09-08 20:24:05.400000          76.0       BUF          left  88.560000  27.01  1.57  0.49  0.15  230.98  147.05           NaN
3        2022090800      56  35472.0  Rodger Saffold        4  2022-09-08 20:24:05.500000          76.0       BUF          left  88.640000  26.90  1.44  0.89  0.14  232.38  145.42           NaN
4        2022090800      56  35472.0  Rodger Saffold        5  2022-09-08 20:24:05.599999          76.0       BUF          left  88.720000  26.80  1.29  1.24  0.13  233.36  141.95           NaN
...             ...     ...      ...             ...      ...                         ...           ...       ...           ...        ...    ...   ...   ...   ...     ...     ...           ...
1407434  2022091200    3826      NaN        football       49  2022-09-12 23:05:57.799999           NaN  football          left  56.220001   9.89  2.56  1.25  0.25     NaN     NaN        tackle
1407435  2022091200    3826      NaN        football       50  2022-09-12 23:05:57.900000           NaN  football          left  56.060001  10.08  2.50  1.14  0.24     NaN     NaN           NaN
1407436  2022091200    3826      NaN        football       51  2022-09-12 23:05:58.000000           NaN  football          left  55.889999  10.27  2.38  1.70  0.25     NaN     NaN           NaN
1407437  2022091200    3826      NaN        football       52  2022-09-12 23:05:58.099999           NaN  football          left  55.730000  10.44  2.07  2.83  0.24     NaN     NaN           NaN
1407438  2022091200    3826      NaN        football       53  2022-09-12 23:05:58.200000           NaN  football          left  55.570000  10.57  1.86  3.00  0.20     NaN     NaN           NaN

[1407439 rows x 17 columns]

In [3]:
first_week.loc[first_week['club'] == 'BUF']

           gameId  playId    nflId        displayName  frameId                        time  jerseyNumber club playDirection      x      y     s     a   dis       o     dir         event
0      2022090800      56  35472.0     Rodger Saffold        1  2022-09-08 20:24:05.200000          76.0  BUF          left  88.37  27.27  1.62  1.15  0.16  231.74  147.90           NaN
1      2022090800      56  35472.0     Rodger Saffold        2  2022-09-08 20:24:05.299999          76.0  BUF          left  88.47  27.13  1.67  0.61  0.17  230.98  148.53  pass_arrived
2      2022090800      56  35472.0     Rodger Saffold        3  2022-09-08 20:24:05.400000          76.0  BUF          left  88.56  27.01  1.57  0.49  0.15  230.98  147.05           NaN
3      2022090800      56  35472.0     Rodger Saffold        4  2022-09-08 20:24:05.500000          76.0  BUF          left  88.64  26.90  1.44  0.89  0.14  232.38  145.42           NaN
4      2022090800      56  35472.0     Rodger Saffold        5  2022-09-08 20:24:05.599999          76.0  BUF          left  88.72  26.80  1.29  1.24  0.13  233.36  141.95           NaN
...           ...     ...      ...                ...      ...                         ...           ...  ...           ...    ...    ...   ...   ...   ...     ...     ...           ...
79167  2022090800    3636  54650.0  Christian Benford       36  2022-09-08 23:05:27.099999          47.0  BUF          left  21.65  33.76  2.33  2.91  0.26  123.91  185.44        tackle
79168  2022090800    3636  54650.0  Christian Benford       37  2022-09-08 23:05:27.200000          47.0  BUF          left  21.64  33.55  1.94  3.17  0.21  122.66  182.97           NaN
79169  2022090800    3636  54650.0  Christian Benford       38  2022-09-08 23:05:27.299999          47.0  BUF          left  21.64  33.39  1.50  3.45  0.17  119.87  176.44           NaN
79170  2022090800    3636  54650.0  Christian Benford       39  2022-09-08 23:05:27.400000          47.0  BUF          left  21.66  33.26  1.17  3.30  0.13  116.81  168.35           NaN
79171  2022090800    3636  54650.0  Christian Benford       40  2022-09-08 23:05:27.500000          47.0  BUF          left  21.71  33.16  0.93  3.19  0.11  112.44  150.25           NaN

[37884 rows x 17 columns]

In [12]:
buf = first_week.loc[first_week['club'] == 'BUF']

ids = buf['gameId'].unique()

for id in ids:
    df = first_week.loc[first_week['gameId'] == id]
    print(df['club'].unique())
    if 'BAL' in df['club'].unique():
        print(df.iloc[0])
    else:
        continue

['BUF' 'LA' 'football']

In [22]:
first_week.loc[first_week['playId'] == 2184]

           gameId  playId    nflId     displayName  frameId                        time  jerseyNumber      club playDirection          x          y     s     a   dis       o     dir         event
43240  2022090800    2184  35472.0  Rodger Saffold        1  2022-09-08 22:01:27.400000          76.0       BUF          left  37.190000  22.050000  1.79  2.80  0.17  286.97   34.95  pass_arrived
43241  2022090800    2184  35472.0  Rodger Saffold        2  2022-09-08 22:01:27.500000          76.0       BUF          left  37.260000  22.180000  1.47  3.57  0.14  296.88   23.83           NaN
43242  2022090800    2184  35472.0  Rodger Saffold        3  2022-09-08 22:01:27.599999          76.0       BUF          left  37.280000  22.300000  1.21  3.27  0.12  298.55    7.42           NaN
43243  2022090800    2184  35472.0  Rodger Saffold        4  2022-09-08 22:01:27.700000          76.0       BUF          left  37.280000  22.400000  1.02  2.82  0.10  298.55  350.77           NaN
43244  2022090800    2184  35472.0  Rodger Saffold        5  2022-09-08 22:01:27.799999          76.0       BUF          left  37.240000  22.430000  0.72  2.62  0.05  299.99  325.69           NaN
...           ...     ...      ...             ...      ...                         ...           ...       ...           ...        ...        ...   ...   ...   ...     ...     ...           ...
44247  2022090800    2184      NaN        football       40  2022-09-08 22:01:31.299999           NaN  football          left  25.629999  30.250000  3.11  2.18  0.35     NaN     NaN        tackle
44248  2022090800    2184      NaN        football       41  2022-09-08 22:01:31.400000           NaN  football          left  25.629999  30.459999  2.62  3.50  0.20     NaN     NaN           NaN
44249  2022090800    2184      NaN        football       42  2022-09-08 22:01:31.500000           NaN  football          left  25.600000  30.700001  2.24  3.85  0.24     NaN     NaN           NaN
44250  2022090800    2184      NaN        football       43  2022-09-08 22:01:31.599999           NaN  football          left  25.639999  30.930000  1.91  3.67  0.23     NaN     NaN           NaN
44251  2022090800    2184      NaN        football       44  2022-09-08 22:01:31.700000           NaN  football          left  25.680000  31.120001  1.59  3.31  0.20     NaN     NaN           NaN

[1012 rows x 17 columns]

In [25]:
df = pd.read_csv('tracking_week_1.csv')
df.loc[df['playId'] == 3229]

Empty DataFrame
Columns: [gameId, playId, nflId, displayName, frameId, time, jerseyNumber, club, playDirection, x, y, s, a, dis, o, dir, event]
Index: []

In [29]:
df.loc[df['playId'] == 2056]

Empty DataFrame
Columns: [gameId, playId, nflId, displayName, frameId, time, jerseyNumber, club, playDirection, x, y, s, a, dis, o, dir, event]
Index: []

In [34]:
test = df.loc[df['nflId'] == 47836]
test.loc[df['gameId'] == 2022110300]

Empty DataFrame
Columns: [gameId, playId, nflId, displayName, frameId, time, jerseyNumber, club, playDirection, x, y, s, a, dis, o, dir, event]
Index: []